### ISSUE TITLE
a new function to make a javascript

### ISSUE THREAD

**Issue by yhoriuchi** [yhoriuchi/projoint#13]
I actually wrote a function to make a Javascript for the second wave of a conjoint experiment. This function can be improved and added to this package. An important merit of this function is that it can be _fully flexible_. A user generates ALL possible profile combinations with appropriate (1) cross-attribute constraints (for each profile), (2) cross-profile constraints, and (3) weights. This function should be super helpful for users who want to estimate many QoIs with constraints and weights. I need someone's help!

**Comment by aaronrkaufman** [comment]
Where is the draft of this function?

**Comment by yhoriuchi** [comment]
See, for example, at the very end of [this script](https://www.dropbox.com/scl/fi/2uzq0wf6n7lfv2l16rrre/02_prepare_javascript.R?rlkey=v36id8gf75ao1lff29nwmk75h&dl=0). It makes `study8_javascript.txt` which we added to the second wave of our study 8. This javascript assigns exactly the same attributes and levels (as those in Wave 1) to each respondent. My idea is to use this function as a start and make a new function. Users should do the following:

1. Specify each attribute as a character vector: e.g., `race <- c("White", "Black", "Asian")`
3. Specify cross-attribute constraints: e.g., `a_const_1 <- list(education = "Graduate degree", occupation = "Janitor")`
4. Specify cross-profile constraints: e.g., `p_const_1 <- list(race_1 = "White", race_2 = "White"` (where _1 and _2 indicate profile numbers)
5. Specify desirable weights after adding these constraints

With all these input arguments, ideally, this function should generate ALL possible profile pairs (with constraints and weight). Then, the javascript to be generated will assign one of the possible profile pairs to each task for each respondent. 

Eventually, we should make a Shiny app to generate this Javascript.

**Comment by aaronrkaufman** [comment]
This is definitely on my to-do list, but I do not want to do this in R or R Shiny. As you know, I am hiring a team of RAs to design a web interface for this. Can we close this for now?

**Comment by yhoriuchi** [comment]
Yes. Please close it.
