### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by yhoriuchi** [yhoriuchi/projoint#15]
We should add a Code of conduct like: 

https://patchwork.data-imaginist.com/CODE_OF_CONDUCT.html

**Comment by aaronrkaufman** [comment]
added this; not sure if it is automatically added to the website or not

**Comment by yhoriuchi** [comment]
You saved the new markdown file but it does not appear on the homepage. Can you revise README.md? ALso, whenver you push a change to "main", `pkgdown:build_site()` wil automatically run. After a few minutes, you should be able to see the change on the website.

**Comment by yhoriuchi** [comment]
devtools::check() shows an error. @aaronrkaufman , can you fix this? 
```
checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘CODE_OF_CONDUCT.md’
```

**Comment by aaronrkaufman** [comment]
I get pkgdown errors whenever I commit; it only updates when you push!

I gave it a second try; please update pkgdown and tell me it worked

**Comment by yhoriuchi** [comment]
You get an error because there is an error in a document:

> pkgdown::build_site()
-- Installing package into temporary library
---------------------------------------------------------------------
== Building pkgdown site
=======================================================
Reading from: '/Users/f000kyp/Dropbox (Personal)/03 Research -
Projects/_RPackages/projoint/projoint'
Writing to:   '/Users/f000kyp/Dropbox (Personal)/03 Research -
Projects/_RPackages/projoint/projoint/docs'
-- Initialising site
-----------------------------------------------------------
-- Building home
---------------------------------------------------------------
Error:
! in callr subprocess.
Caused by error in `parse(con)`:
! 10:21: unexpected symbol
9:   publisher = {GitHub},
10:   journal = {GitHub repository
                        ^
ℹ See `$stdout` for standard output.
Type .Last.error to see the more details.

**Comment by aaronrkaufman** [comment]
fixed
