### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by yhoriuchi** [yhoriuchi/projoint#16]
The citation page should be improved. We should add a Bibtex entry for our main paper. See the following as an example.

https://declaredesign.org/r/declaredesign/authors.html#citation

I assume that the "authors" of `projoint` will be Aaron and me.

**Comment by aaronrkaufman** [comment]
I added a CITATION file as per declaredesign; not sure how to make it show up on pkgdown

**Comment by yhoriuchi** [comment]
@aaronrkaufman , can you fix this? 
```
❯ checking package subdirectories ... WARNING
  Invalid citation information in ‘inst/CITATION’:
    Error in parse(con): 10:21: unexpected symbol
    9:   publisher = {GitHub},
    10:   journal = {GitHub repository
                            ^
```

**Comment by aaronrkaufman** [comment]
Weird, I wonder if it doesn't like the whitespace character. I tried again

**Comment by aaronrkaufman** [comment]
fixed
