### ISSUE TITLE
Revise 03. Predict the intra-respondent reliability (IRR)

### ISSUE THREAD

**Issue by yhoriuchi** [yhoriuchi/projoint#18]
We should use `summary()` and `plot()`. Do we need `print()` for `predict_tau()`?

**Comment by aaronrkaufman** [comment]
I don't understand -- do you want me to remove the print() method? Is that it?

**Comment by yhoriuchi** [comment]
I don't quite understand the merit of print() for predict_tau(). Users only
want to show the estimated IRR and plot the figure. Wha does print() do?

**Comment by aaronrkaufman** [comment]
We can definitely remove it, but we can also keep it in if we decide to expand on it later. Currently, it is not harmful and it contains different information from summary()

**Comment by yhoriuchi** [comment]
OK! Then, can you revise the vignette and close this issue?
