### ISSUE TITLE
estimation without reshaping

### ISSUE THREAD

**Issue by ataustin06** [yhoriuchi/projoint#20]
Hello! I have already reshaped my data. How can I run an error-corrected mm or amce estimation without using your reshaping function?

**Comment by yhoriuchi** [comment]
Hi @ataustin06 . Thank you for posting the question. I understand that some people have already reshaped the data using other packages or writing their own scripts. What is the unit of observations in your reshaped data? As long as it is `respondent`-`task`-`id`, then it is not very difficult to make a new function (by me) to generate an object with the `projoint_data` class.

**Comment by ataustin06** [comment]
Yes, it is in the format of respondent - task - id. Specifically, I have id numbers for each respondent, a choice preference between two profiles, and id numbers for each experimental iteration. My data also includes traits for the profile chosen and not chosen, an identifier for the repeated experimental iteration, and respondent characteristics for estimating conditional amce's. Thank you for your response and your assistance!

**Comment by yhoriuchi** [comment]
Can you send me your data by email? (You don't need to post your data here). If you prefer, you can send me just the first 20-50 rows. I need to have a look at how your data frame is structured.

**Comment by ataustin06** [comment]
Yes, I can send you the first few rows of the data scrubbed of identifiers.

**Comment by ataustin06** [comment]
Hi Yusaku,

I am sending the entire scrubbed dataset because I think you will need
all of it to see the structure. I plan to publish the dataset anyway
for replication and open science purposes. Please note that my
conjoint set-up differs slightly from the norm in that it has only one
level, but 15 attributes in this level.

The variables are:

- id.num: identification numbers for each respondent,
- vote_for.factor: a binary choice preference between two profiles,
- exp: a number assigned to each iteration of the experiment, 1-16,
- traits.factor: a character description of the profile attributes,
- repeat.factor: a binary variable indicating whether an experimental
iteration was repeated or not,
- ideo.factor:  a factor variable with 7 levels describing respondent
ideology, and
- party.factor: a factor variable with 5 levels describing respondent
party affiliation.

Let me know if you need any additional variables or information.

Thank you again,
Amanda

P.S. You will be going in my paper's acknowledgments section!

**Comment by yhoriuchi** [comment]
I made a new function named `make_projoint_data.R` and added a new section (2.4 Read your already-wrangled tibble) to the second vignette. I now close this issue! Thank you, @ataustin06 , for your question. @aaronrkaufman , please check the Roxygen2 documentation and the vignettes.
